"""
Alle Gruppen-Konstanten werden in dieser Datei definiert.
"""

ADMIN                               = 'admin'
MANAGEMENT                          = 'management'
CUSTOMERS                           = 'customers'
C1                                  = 'customer 1'
C2                                  = 'customer 2'
C3                                  = 'customer 3'
CUSTOMER_SERVICE                    = 'customer service'
INTERNAL_SERVICE                    = 'internal service'
PRODUCTION_SERVICE                  = 'production service'
PRODUCTION                          = 'production'
SUPPLIERS                           = 'suppliers'
S100                                = 'supplier 100'
S200                                = 'supplier 200'
S300                                = 'supplier 300'
GAME_MASTER                         = 'game master'
JOGA                                = 'JOGA'

#Gruppen-Kuerzel
ADMIN_CODE                          = 'ADM'
MANAGEMENT_CODE                     = 'MG'
CUSTOMERS_CODE                      = 'C'
C1_CODE                             = 'C1'
C2_CODE                             = 'C2'
C3_CODE                             = 'C3'
CUSTOMER_SERVICE_CODE               = 'CS'
INTERNAL_SERVICE_CODE               = 'ITS'
PRODUCTION_SERVICE_CODE             = 'PRS'
PRODUCTION_CODE                     = 'PRO'
SUPPLIERS_CODE                      = 'SUP'
S100_CODE                           = 'S1'
S200_CODE                           = 'S2'
S300_CODE                           = 'S3'
GAME_MASTER_CODE                    = 'GM'
JOGA_CODE                           = 'JOG'