"""
Alle Gruppen-Konstanten werden in dieser Datei definiert.
"""

ADMIN                               = 'Admin'
LEITUNGSTEAM                        = 'Geschäftsleitung'
KUNDEN                              = 'Kunden'
K1                                  = 'Kunde 1'
K2                                  = 'Kunde 2'
K3                                  = 'Kunde 3'
KUNDENDIENST                        = 'Kundendienst'
INTERNE_DIENSTLEISTUNG              = 'Interne Dienstleistung'
PRODUKTIONSDIENSTLEISTUNG           = 'Produktionsdienstleistung'
PRODUKTION                          = 'Produktion'
LIEFERANTEN                         = 'Lieferanten'
L100                                = 'Lieferant 100'
L200                                = 'Lieferant 200'
L300                                = 'Lieferant 300'
SPIELLEITUNG                        = 'Spielleitung'
JOGA                                = 'JOGA'

#Gruppen-Kuerzel
ADMIN_CODE                          = 'ADM'
LEITUNGSTEAM_CODE                   = 'LT'
KUNDEN_CODE                         = 'K'
K1_CODE                             = 'K1'
K2_CODE                             = 'K2'
K3_CODE                             = 'K3'
KUNDENDIENST_CODE                   = 'KD'
INTERNE_DIENSTLEISTUNG_CODE         = 'IDL'
PRODUKTIONSDIENSTLEISTUNG_CODE      = 'PDL'
PRODUKTION_CODE                     = 'PRO'
LIEFERANTEN_CODE                    = 'L'
L100_CODE                           = 'L100'
L200_CODE                           = 'L200'
L300_CODE                           = 'L300'
SPIELLEITUNG_CODE                   = 'SL'
JOGA_CODE                           = 'JOG'