#The amount of players for each organisational unit are defined here

PLAYER_AMOUNT_LEITUNGSTEAM              = 3
PLAYER_AMOUNT_KUNDEN                    = 3
PLAYER_AMOUNT_KUNDENDIENST              = 3
PLAYER_AMOUNT_INTERNE_DIENSTLEISTUNG    = 3
PLAYER_AMOUNT_PRODUKTIONSDIENSTLEISTUNG = 3
PLAYER_AMOUNT_PRODUKTION                = 3
PLAYER_AMOUNT_LIEFERANTEN               = 3
PLAYER_AMOUNT_SPIELLEITUNG              = 1