"""
Die Anzahl der Spieler jeder Organisationseinheit sind hier definiert.
"""

PLAYER_AMOUNT_MANAGEMENT          = 3
PLAYER_AMOUNT_CUSTOMERS           = 3
PLAYER_AMOUNT_CUSTOMER_SERVICE    = 3
PLAYER_AMOUNT_INTERNAL_SERVICE    = 3
PLAYER_AMOUNT_PRODUCTION_SERVICE  = 3
PLAYER_AMOUNT_PRODUCTION          = 3
PLAYER_AMOUNT_SUPPLIERS           = 3
PLAYER_AMOUNT_GAME_MASTER         = 1