from django.contrib import admin
from gtapp.models import *

# Register your models here.
admin.site.register(Article)
admin.site.register(ArtiPart)
admin.site.register(BookingCode)
admin.site.register(CustComplaint)
admin.site.register(CustComplaintDet)
admin.site.register(CustContainer)
admin.site.register(Customer)
admin.site.register(CustOrder)
admin.site.register(CustOrderDet)
admin.site.register(Message)
admin.site.register(MessageTemplate)
admin.site.register(Part)
admin.site.register(Player)
admin.site.register(Status)
admin.site.register(Stock)
admin.site.register(StockMovement)
admin.site.register(SuppComplaint)
admin.site.register(SuppComplaintDet)
admin.site.register(SuppContainer)
admin.site.register(Supplier)
admin.site.register(SuppOrder)
admin.site.register(SuppOrderDet)
admin.site.register(Todo)
admin.site.register(TodoType)
admin.site.register(LiveSettings)
admin.site.register(Timers)
