# Generated by Django 3.1.2 on 2020-11-30 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_no', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='CustComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('finished_on', models.SmallIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('memo', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=8)),
                ('price', models.SmallIntegerField()),
                ('issued_on', models.SmallIntegerField()),
                ('delivery_date', models.SmallIntegerField()),
                ('received_on', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('costumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.customer')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_no', models.CharField(max_length=8)),
                ('description', models.CharField(max_length=30)),
                ('unit_price', models.SmallIntegerField(null=True)),
                ('picture', models.BinaryField(null=True)),
                ('pack_quantity', models.SmallIntegerField()),
                ('install_quantity', models.SmallIntegerField()),
                ('initial_stock', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=1)),
                ('description_en', models.CharField(max_length=30)),
                ('description_de', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='SuppComplaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('finished_on', models.SmallIntegerField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('memo', models.TextField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='SuppOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_no', models.CharField(max_length=8)),
                ('price', models.SmallIntegerField()),
                ('issued_on', models.SmallIntegerField()),
                ('delivery_date', models.SmallIntegerField()),
                ('received_on', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.supplier')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.SmallIntegerField()),
                ('cust_order_det', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('finished_on', models.SmallIntegerField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='SuppOrderDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('received_on', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.part')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
                ('supp_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.supporder')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuppContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supp_order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.supporderdet')),
            ],
        ),
        migrations.CreateModel(
            name='SuppComplaintDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.TextField()),
                ('finished_on', models.SmallIntegerField()),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
                ('supp_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.suppcomplaint')),
                ('supp_order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.supporderdet')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.SmallIntegerField()),
                ('reserved', models.SmallIntegerField(default=0)),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.part')),
            ],
        ),
        migrations.AddField(
            model_name='part',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status'),
        ),
        migrations.AddField(
            model_name='part',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.supplier'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sent_on', models.SmallIntegerField()),
                ('received_on', models.SmallIntegerField()),
                ('read_on', models.SmallIntegerField()),
                ('receiver', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sender', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
        ),
        migrations.CreateModel(
            name='CustOrderDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.IntegerField()),
                ('unit_price', models.IntegerField()),
                ('received_on', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.article')),
                ('cust_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.custorder')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='custorder',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status'),
        ),
        migrations.AddField(
            model_name='custorder',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status'),
        ),
        migrations.CreateModel(
            name='CustContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=8)),
                ('delivery_date', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('cust_order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.custorderdet')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustComplaintDet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pos', models.SmallIntegerField()),
                ('quantity', models.SmallIntegerField()),
                ('memo', models.TextField()),
                ('cust_complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.custcomplaint')),
                ('cust_order_det', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.custorderdet')),
                ('status', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='custcomplaint',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status'),
        ),
        migrations.AddField(
            model_name='custcomplaint',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='ArtiPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.SmallIntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.article')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gtapp.part')),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='parts',
            field=models.ManyToManyField(through='gtapp.ArtiPart', to='gtapp.Part'),
        ),
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gtapp.status'),
        ),
    ]
